<?php
/* 
     // ======================================== \
     // Package: ImgPizza
     // Version: 5.0.0
     // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
     // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
     // LTE: 1403964436 - Saturday, June 28, 2014, 10:07:16 AM EDT -0400
     // ======================================== /
     
     This file contains some language settings that are a part of ImgPizza but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by ImgPizza; so be careful while editing to not remove them.
     
     Language file index:
		001 -- Initial page title for information page
		002 -- Extended page title for about us page
		003 -- Extended page title for terms of service page
		004 -- Extended page title for privacy policy page
		005 -- Error to be displayed if no page parameter is given

*/
    
	$mmhclass->lang['001'] = "%s -";
	$mmhclass->lang['002'] = "About Us";
	$mmhclass->lang['003'] = "Terms of Service";
	$mmhclass->lang['004'] = "Privacy Policy";
	$mmhclass->lang['005'] = "You have reached this page in error. Please use your back button to return to the previous page.";


?>