<?php
/* 
     // ======================================== \
     // Package: ImgPizza
     // Version: 5.0.0
     // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
     // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
     // LTE: $ModificationDate
     // ======================================== /
     
     This file contains some language settings that are a part of ImgPizza but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by ImgPizza; so be careful while editing to not remove them.
     
     Language file index:
$LanguageIndex
*/
    
$LanguageSettings

?>